### ISSUE TITLE
Explain technical nuances of trading on drift

### ISSUE THREAD

**Issue by wphan** [drift-labs/drift-docs-v2#30]
There are some limitations to trading on drift that users might not expect coming from other CEX/DEXs:
* each subaccount can only hold up to 8 perp positions and 8 spot positions (balances)
  * a perp position with 0 base but only unsettled pnl counts as an open position
* each subaccount can only hold up to 32 open orders
* settling pnl is permissionless and can be triggered by anyone
* funding is settled lazily, funding payments may not pay out for markets that trade infrequently
* spot deposit/borrow interest is paid out continuously and directly to the spot balance, there are no records of interest paid/received or cumulative interest

**Comment by xentoshi** [comment]
added all of these in their respective pages 
[/managing-subacount.mdx](https://github.com/drift-labs/drift-docs-v2/blob/d44940d8b5078a66811790436f5967cf0f60001e/pages/getting-started/managing-subaccount.mdx)
[/profit-loss-intro.mdx](https://github.com/drift-labs/drift-docs-v2/blob/d44940d8b5078a66811790436f5967cf0f60001e/pages/profit-loss/profit-loss-intro.mdx)
[/funding-rates.mdx](https://github.com/drift-labs/drift-docs-v2/blob/d44940d8b5078a66811790436f5967cf0f60001e/pages/trading/funding-rates.mdx#L4)
[/supply-borrow-apy.mdx](https://github.com/drift-labs/drift-docs-v2/blob/main/pages/lend-borrow/supply-borrow-apy.mdx)
